// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reports.DataAccess;

namespace Reports.DataAccess.Migrations
{
    [DbContext(typeof(ReportsContext))]
    partial class ReportsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reports.Domain.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConnectionString")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("Reports.Domain.AreaManager", b =>
                {
                    b.Property<Guid>("AreaId");

                    b.Property<Guid>("ManagerId");

                    b.HasKey("AreaId", "ManagerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("AreaManager");
                });

            modelBuilder.Entity("Reports.Domain.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AreaId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Components");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Component");
                });

            modelBuilder.Entity("Reports.Domain.Indicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AreaId");

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<Guid?>("ComponentId");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ComponentId");

                    b.ToTable("Indicators");
                });

            modelBuilder.Entity("Reports.Domain.IndicatorDisplay", b =>
                {
                    b.Property<Guid>("AreaId");

                    b.Property<Guid>("UserId");

                    b.Property<Guid>("IndicatorId");

                    b.Property<Guid>("Id");

                    b.Property<int>("Orden");

                    b.Property<Guid>("User");

                    b.Property<bool>("Visible");

                    b.HasKey("AreaId", "UserId", "IndicatorId");

                    b.HasIndex("IndicatorId");

                    b.ToTable("IndicatorDisplay");
                });

            modelBuilder.Entity("Reports.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Admin");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Reports.Domain.ValueExpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ValueExpressions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ValueExpression");
                });

            modelBuilder.Entity("Reports.Domain.Condition", b =>
                {
                    b.HasBaseType("Reports.Domain.Component");

                    b.Property<string>("Operation");

                    b.Property<Guid?>("ValueDerId");

                    b.Property<Guid?>("ValueIzqId");

                    b.HasIndex("ValueDerId");

                    b.HasIndex("ValueIzqId");

                    b.HasDiscriminator().HasValue("Condition");
                });

            modelBuilder.Entity("Reports.Domain.LogicAnd", b =>
                {
                    b.HasBaseType("Reports.Domain.Component");

                    b.Property<Guid?>("CompDerId");

                    b.Property<Guid?>("CompIzqId");

                    b.HasIndex("CompDerId");

                    b.HasIndex("CompIzqId");

                    b.HasDiscriminator().HasValue("LogicAnd");
                });

            modelBuilder.Entity("Reports.Domain.LogicOr", b =>
                {
                    b.HasBaseType("Reports.Domain.Component");

                    b.Property<Guid?>("CompDerId")
                        .HasColumnName("LogicOr_CompDerId");

                    b.Property<Guid?>("CompIzqId")
                        .HasColumnName("LogicOr_CompIzqId");

                    b.HasIndex("CompDerId");

                    b.HasIndex("CompIzqId");

                    b.HasDiscriminator().HasValue("LogicOr");
                });

            modelBuilder.Entity("Reports.Domain.IntValue", b =>
                {
                    b.HasBaseType("Reports.Domain.ValueExpression");

                    b.HasDiscriminator().HasValue("IntValue");
                });

            modelBuilder.Entity("Reports.Domain.SQLValue", b =>
                {
                    b.HasBaseType("Reports.Domain.ValueExpression");

                    b.Property<Guid?>("AreaId");

                    b.HasIndex("AreaId");

                    b.HasDiscriminator().HasValue("SQLValue");
                });

            modelBuilder.Entity("Reports.Domain.StringValue", b =>
                {
                    b.HasBaseType("Reports.Domain.ValueExpression");

                    b.HasDiscriminator().HasValue("StringValue");
                });

            modelBuilder.Entity("Reports.Domain.AreaManager", b =>
                {
                    b.HasOne("Reports.Domain.Area", "Area")
                        .WithMany("AreaManagers")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Reports.Domain.User", "Manager")
                        .WithMany("AreaManagers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Reports.Domain.Indicator", b =>
                {
                    b.HasOne("Reports.Domain.Area")
                        .WithMany("Indicators")
                        .HasForeignKey("AreaId");

                    b.HasOne("Reports.Domain.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");
                });

            modelBuilder.Entity("Reports.Domain.IndicatorDisplay", b =>
                {
                    b.HasOne("Reports.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Reports.Domain.Indicator", "Indicator")
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Reports.Domain.Condition", b =>
                {
                    b.HasOne("Reports.Domain.ValueExpression", "ValueDer")
                        .WithMany()
                        .HasForeignKey("ValueDerId");

                    b.HasOne("Reports.Domain.ValueExpression", "ValueIzq")
                        .WithMany()
                        .HasForeignKey("ValueIzqId");
                });

            modelBuilder.Entity("Reports.Domain.LogicAnd", b =>
                {
                    b.HasOne("Reports.Domain.Component", "CompDer")
                        .WithMany()
                        .HasForeignKey("CompDerId");

                    b.HasOne("Reports.Domain.Component", "CompIzq")
                        .WithMany()
                        .HasForeignKey("CompIzqId");
                });

            modelBuilder.Entity("Reports.Domain.LogicOr", b =>
                {
                    b.HasOne("Reports.Domain.Component", "CompDer")
                        .WithMany()
                        .HasForeignKey("CompDerId");

                    b.HasOne("Reports.Domain.Component", "CompIzq")
                        .WithMany()
                        .HasForeignKey("CompIzqId");
                });

            modelBuilder.Entity("Reports.Domain.SQLValue", b =>
                {
                    b.HasOne("Reports.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");
                });
#pragma warning restore 612, 618
        }
    }
}
